name: faculty_research_app
description: A mobile application for managing faculty research details.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ---------- Firebase ----------
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0

  # ---------- Supabase ----------
  supabase_flutter: ^2.5.3

  # ---------- Image Picker ----------
  image_picker: ^1.0.7

  # ---------- UI ----------
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

